### ISSUE TITLE
Zoomed in view occasionally not displaying entire label

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/notesFromNature#304]
Not having the entire label in view makes it pretty hard to transcribe.

Work has begun to fix this in the interface branch. I'll post updates here.

**Comment by denslowm** [comment]
Instead of starting a new issue, I wonder if we can request that the zoom be added to Macrofungi as well? That would resolve this issue.

I think this is working great for the herbarium interface and our volunteers seem to like it as well.
http://talk.notesfromnature.org/#/boards/BNN0000002/discussions/DNN00003yb?page=1&comment_id=5512d93b90ecf52b8d00028e
